encoder_odom:
  ros__parameters:
    wheel_radius_m: 0.04
    wheel_separation_m: 0.5
    ticks_per_rev: 3459.0

transforms:
  base_to_laser:
    x: 0.0
    y: 0.0
    z: 0.2032
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    parent_frame: "base_link"
    child_frame: "laser"
  
  base_to_camera:
    x: 0.0
    y: 0.2159
    z: 0.1651
    roll: -1.57079632679
    pitch: 0.0
    yaw: 0.0
    parent_frame: "base_link"
    child_frame: "oak_parent_frame"

