odometry:
  ros__parameters:
    bus: 1
    addr: 0x31
    endian: "little"
    publish_rate_hz: 30.0
    pod_offsets_mm: [160.87, -201.3]
    encoder_directions: [True, True]
    odom_frame: "odom"
    base_frame: "base_link"

transforms:
  base_to_laser:
    x: 0.0
    y: 0.0
    z: 0.2032
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    parent_frame: "base_link"
    child_frame: "laser"
  
  base_to_camera:
    x: 0.0
    y: 0.2159
    z: 0.1651
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    parent_frame: "base_link"
    child_frame: "camera_link"

